---
esphome:
  name: ${device_name}

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf
    version: recommended

packages:
  core: !include ../common/core.yaml

sensor:
 - <<: !include ../common/sensor/wifi_signal.yaml

text_sensor:
 - <<: !include ../common/text_sensor/wifi_info.yaml

button:
  - <<: !include ../common/button/restart.yaml

time:
  - <<: !include ../common/time/sntp.yaml

select:
  - <<: !include ../common/select/select_logger.yaml
