---
esphome:
    name: ${device_name}

esp8266:
    board: esp12e

packages:
  core: !include ../common/core.yaml

sensor:
  - <<: !include ../common/sensor/wifi_signal.yaml

text_sensor:
  - <<: !include ../common/text_sensor/wifi_info.yaml

button:
  - <<: !include ../common/button/restart.yaml

select:
  - <<: !include ../common/select/select_logger.yaml

time:
  - <<: !include ../common/time/sntp.yaml

output:
  - platform: esp8266_pwm
    pin: GPIO2
    id: red_1
  - platform: esp8266_pwm
    pin: GPIO0
    id: green_1
  - platform: esp8266_pwm
    pin: GPIO4
    id: blue_1
  - platform: esp8266_pwm
    pin: GPIO5
    id: cw_1
  - platform: esp8266_pwm
    pin: GPIO3
    id: ww_1

light:
  - platform: rgbww
    name: luz
    id: light_1
    red: red_1
    green: green_1
    blue: blue_1
    cold_white: cw_1
    warm_white: ww_1
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    color_interlock: true
