---
esphome:
  name: ${device_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

status_led:
  pin:
    number: GPIO19
    inverted: true

packages:
  api: !include ../common/api.yaml
  wifi: !include ../common/wifi.yaml
  ota: !include ../common/ota.yaml
  logger: !include ../common/logger.yaml
  web_server: !include ../common/web_server.yaml
  captive_portal: !include ../common/captive_portal.yaml
  syslog: !include ../common/syslog.yaml

text_sensor:
  - <<: !include ../common/text_sensor/wifi_info.yaml

button:
  - <<: !include ../common/button/restart.yaml

select:
  - <<: !include ../common/select/select_logger.yaml

time:
  - <<: !include ../common/time/sntp.yaml

output:
  - platform: gpio
    pin: GPIO26
    id: relay_1

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
      inverted: false
    id: s1
    name: switch
    internal: true
    filters:
      - invert:
      - delayed_on_off: 50ms
  - platform: gpio
    pin:
      number: GPIO00
      ignore_strapping_warning: true
    id: button_1
    internal: true