---
esphome:
  name: ${device_name}

esp8266:
  board: esp8285

status_led:
    pin:
      number: GPIO13
      inverted: true

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

binary_sensor:
  - platform: gpio
    pin: GPIO0
    id: button_1
    internal: true

packages:
  core: !include ../common/core.yaml

sensor:
 - <<: !include ../common/sensor/wifi_signal.yaml

text_sensor:
 - <<: !include ../common/text_sensor/wifi_info.yaml

button:
  - <<: !include ../common/button/restart.yaml

select:
  - <<: !include ../common/select/select_logger.yaml

time:
  - <<: !include ../common/time/sntp.yaml
