substitutions:
  device_name: ac-luz-principal-estudio

packages:
  device_base: !include base_devices/sonoffmini.yaml
  mqtt: !include common/mqtt.yaml

esphome:
  friendly_name: Alimentación luz principal estudio
  area: estudio
  on_boot:
    priority: 600
    then:
      - output.turn_on: relay_1

binary_sensor:
  - id: !extend switch_1
    on_state:
      then:
        - mqtt.publish_json:
            topic: luz-principal-estudio/light/luz/command
            payload: |-
              root["state"] = "TOGGLE";

switch:
  - platform: output
    name: "AC"
    output: 'relay_1'
    restore_mode: ALWAYS_ON