substitutions:
  device_name: ac-lavadora

packages:
  device_base: !include base_devices/sonoffs60.yaml

esphome:
  friendly_name: Alimentación lavadora
  comment: Sonoff S60 que mide y controla la alimentación de la lavadora.
  area: cocina
