substitutions:
  device_name: ac-luz-entrada-estudio
  light_device_name: luz-entrada-estudio

packages:
  device_base: !include base_devices/sonoffmini.yaml
  behavior: !include common/behaviors/always_on_mqtt_light_relay.yaml

esphome:
  friendly_name: Alimentación luz entrada estudio
  comment: Sonoff Mini que controla la alimentación de la luminaria de entrada.
  area: estudio
