substitutions:
  device_name: ac-luz-principal-salon
  light_device_name: luz-principal-salon

packages:
  device_base: !include base_devices/sonoffmini.yaml
  behavior: !include common/behaviors/always_on_mqtt_light_relay.yaml

esphome:
  friendly_name: Alimentación luz principal salón
  area: salon
