substitutions:
  device_name: ac-luz-principal-estudio
  light_device_name: luz-principal-estudio

packages:
  device_base: !include base_devices/sonoffmini.yaml
  behavior: !include common/behaviors/always_on_mqtt_light_relay.yaml

esphome:
  friendly_name: Alimentación luz principal estudio
  comment: Sonoff Mini que controla la alimentación de la luminaria principal.
  area: estudio
