substitutions:
  device_name: ac-luz-entrada-salon
  light_device_name: luz-entrada-salon

packages:
  device_base: !include base_devices/sonoffmini.yaml
  behavior: !include common/behaviors/always_on_mqtt_light_relay.yaml

esphome:
  friendly_name: Alimentación luz entrada salón
  area: salon
