substitutions:
  device_name: arenero-gato

packages:
  device_base: !include base_devices/esp12f.yaml

esphome:
  friendly_name: Arenero gatos
  area: bano_pasillo


uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 115200

tuya:
  time_id: sntp_time


switch:
  - platform: tuya
    name: Limpiar
    id: start
    icon: mdi:broom
    switch_datapoint: 3

  - platform: tuya
    name: Limpieza automática
    icon: mdi:robot-vacuum
    id: auto_clean
    switch_datapoint: 4

  - platform: tuya
    name: Deodorizador
    id: deodorization
    icon: mdi:leaf
    switch_datapoint: 17

  - platform: tuya
    name: Bloqueo infantil
    id: child_lock
    icon: mdi:lock
    switch_datapoint: 103

  - platform: tuya
    name: Infrarrojo
    id: infrared
    icon: mdi:motion-sensor
    switch_datapoint: 104

  - platform: tuya
    name: Luz panel
    id: panel_light
    icon: mdi:lightbulb
    inverted: true
    switch_datapoint: 106

  - platform: tuya
    name: Cambiar arena
    id: replace_litter
    icon: mdi:autorenew
    switch_datapoint: 111

  - platform: tuya
    name: Inicilizar arenero
    id: initialize_litter_box
    icon: mdi:restart
    switch_datapoint: 115

  - platform: tuya
    name: Cambiar bolsa
    id: replace_bag
    icon: mdi:delete-empty
    switch_datapoint: 117

  - platform: tuya
    name: Calibrar peso
    id: calibrate_weight
    icon: mdi:scale-balance
    switch_datapoint: 118

number:
  - platform: tuya
    name: Tiempo para comenzar la limpieza
    id: delay_clean_time
    icon: mdi:clock-start
    number_datapoint: 5
    min_value: 0
    max_value: 60
    step: 1
    unit_of_measurement: 'min'

  - platform: tuya
    name: Intervalo entre limpiezas
    id: cleaning_interval
    number_datapoint: 105
    min_value: 0
    max_value: 120
    icon: mdi:timelapse
    step: 1
    unit_of_measurement: 'min'

  - platform: tuya
    name: Umbral de bolsa llena
    id: full_bag_threshold
    number_datapoint: 114
    min_value: 0
    max_value: 15
    step: 1


sensor:
  - platform: tuya
    name: Peso gato
    unit_of_measurement: 'g'
    icon: mdi:scale
    device_class: weight
    id: cat_weight
    sensor_datapoint: 6
    # internal: true
    on_value:
      then:
        - lambda: |-
            if (id(cat_weight).state >= 5001 && id(cat_weight).state <= 8000) {
              return id(weight_cat1).publish_state(x);}
            else if (id(cat_weight).state >= 3500 && id(cat_weight).state <= 5000) {
              return id(weight_cat2).publish_state(x);}
  - platform: tuya
    name: Excreciones del dia
    id: excretion_times_day
    unit_of_measurement: 'veces'
    icon: mdi:counter
    state_class: total_increasing
    sensor_datapoint: 7

  - platform: tuya
    name: Tiempo ultima excreccion
    unit_of_measurement: 's'
    icon: mdi:clock-time-four-outline
    device_class: duration
    state_class: measurement
    id: excretion_time
    sensor_datapoint: 8

  - platform: tuya
    name: Temperatura
    id: temperature
    unit_of_measurement: '°C'
    icon: mdi:thermometer
    device_class: temperature
    state_class: measurement
    sensor_datapoint: 101

  - platform: tuya
    name: Humedad
    id: humidity
    unit_of_measurement: '%'
    icon: mdi:water-percent
    device_class: humidity
    state_class: measurement
    sensor_datapoint: 102

  - platform: tuya
    name: Peso en tiempo real
    unit_of_measurement: 'g'
    icon: mdi:scale
    device_class: weight
    id: real_time_weight
    sensor_datapoint: 116

  - platform: template
    name: Peso Simba
    id: weight_cat1
    unit_of_measurement: 'g'
    device_class: weight
    icon: mdi:weight-kilogram

  - platform: template
    name: Peso Fada
    id: weight_cat2
    unit_of_measurement: 'g'
    device_class: weight
    icon: mdi:weight-kilogram