substitutions:
  device_name: asistente-voz

packages:
  device_base: !include base_devices/esp32s3.yaml

esphome:
  friendly_name: Asistente Voz
  area: Estudio

api:
  on_client_connected:
        then:
          - delay: 50ms
          - micro_wake_word.start:
  on_client_disconnected:
        then:
          - voice_assistant.stop: 

psram:
  mode: octal
  speed: 120MHz

switch:
  - platform: template
    id: mute
    name: "Mute microphone"
    optimistic: true
    on_turn_on: 
      - micro_wake_word.stop:
      - voice_assistant.stop:
    on_turn_off:
      - micro_wake_word.start:

i2s_audio:
  - id: i2s # For microphone
    i2s_lrclk_pin: GPIO40  #WS 
    i2s_bclk_pin: GPIO41 #SCK

microphone:
  - platform: i2s_audio
    id: va_mic
    adc_type: external
    i2s_din_pin: GPIO42 #SD
    channel: left
    i2s_audio_id: i2s
#   pdm: false
#   bits_per_sample: 32bit

output:
  - platform: gpio
    pin: 
      number: GPIO39
      allow_other_uses: true
    id: set_low_speaker

speaker:
    platform: i2s_audio
    id: va_speaker
    i2s_audio_id: i2s
    dac_type: external
    i2s_dout_pin:   
      number: GPIO39 #DIN Pin of the MAX98357A Audio Amplifier
      allow_other_uses: true    
    channel: mono
    bits_per_sample: 32bit
    sample_rate: 16000

micro_wake_word:
  models:
    - model: alexa
  on_wake_word_detected:
    - voice_assistant.start:
    
voice_assistant:
  id: va
  microphone: va_mic
  speaker: va_speaker
  noise_suppression_level: 2.0
  volume_multiplier: 4.0
  on_error:
    - micro_wake_word.start:
  on_end:
        then:
          - wait_until:
              not:
                voice_assistant.is_running:
          - micro_wake_word.start:   