substitutions:
  device_name: dht-trastero

packages:
  device_base: !include base_devices/esp01.yaml

esphome:
  friendly_name: Temperatura y humedad trastero
  comment: ESP-01 con sensor SI7021 de temperatura y humedad.
  area: trastero

sensor:
  - platform: dht
    model: SI7021
    pin: GPIO3
    temperature:
      name: Temperatura
    humidity:
      name: Humedad
