substitutions:
  device_name: fuente-gato

packages:
  device_base: !include base_devices/esp32c3.yaml

esphome:
  friendly_name: Fuente Simba
  area: cocina

uart:
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 9600

tuya:
  time_id: sntp_time
  on_datapoint_update:
    - sensor_datapoint: 23
      datapoint_type: bitmask
      then: 
        - lambda: |-
            uint32_t bitmask_value = x;
            id(bitmask_val) = bitmask_value;
            ESP_LOGD("custom", "Valor de bitmask en datapoint 23: %u", bitmask_value);

switch:
  - platform: tuya
    name: Fuente
    id: fountain
    switch_datapoint: 1
  - platform: tuya
    id: filter_reset
    switch_datapoint: 5
    internal: true
  - platform: tuya
    id: pump_reset
    switch_datapoint: 6
    internal: true
  - platform: tuya
    id: smart_mode
    switch_datapoint: 102
    internal: true

light:
  - platform: tuya
    name: Led
    switch_datapoint: 101
    restore_mode: RESTORE_DEFAULT_ON

select:
  - platform: tuya
    enum_datapoint: 2
    optimistic: true
    id: fountain_mode
    options:
      0: Continue
      1: Intermitent
    internal: true
  - platform: template
    name: Modo
    id: mode_select
    icon: mdi:fountain
    options:
      - Apagado
      - Continuo
      - Intermitente
      - Inteligente
    update_interval: 1s
    lambda: |-
      if (!id(fountain).state) {
        return {"Apagado"};
      } else if (id(fountain_mode).active_index() == 0 && !id(smart_mode).state) {
        return {"Continuo"};
      } else if (id(fountain_mode).active_index() == 1 && !id(smart_mode).state) {
        return {"Intermitente"};
      } else if (id(smart_mode).state) {
        return {"Inteligente"};
      } else {
        return {"Apagado"};
      }
    set_action:
      - lambda: |-
          if (x == "Apagado") {
            id(fountain).turn_off();
          } else if (x == "Continuo") {
            id(fountain).turn_on();
            id(smart_mode).turn_off();
            id(fountain_mode).make_call().set_index(0).perform();
          } else if (x == "Intermitente") {
            id(fountain).turn_on();
            id(smart_mode).turn_off();
            id(fountain_mode).make_call().set_index(1).perform();
          } else if (x == "Inteligente") {
            id(fountain).turn_on();
            id(smart_mode).turn_on();
          }

sensor:
  - platform: tuya
    name: Dias para cambio de filtro
    id: filter_days
    sensor_datapoint: 3
  - platform: tuya
    name: Dias para limpiar
    id: pump_time
    sensor_datapoint: 4

number:
  - platform: tuya
    name: Dias para cambio de filtro
    id: filter_life
    min_value: 0
    step: 1
    max_value: 100
    number_datapoint: 7
  - platform: tuya
    name: Dias para limpiar
    id: time_clean
    step: 1
    min_value: 0
    max_value: 100
    number_datapoint: 8

button:
  - platform: template
    name: Restablecer Filtro
    on_press:
      then:
        - switch.turn_on: filter_reset
  - platform: template
    name: Restablecer limpieza
    on_press:
      then:
        - switch.turn_on: pump_reset

binary_sensor:
  - platform: template
    name: Error General
    id: problem
    device_class: problem
    lambda: |-
      return id(bitmask_val) != 0;

  - platform: template
    name: Limpiar Filtro
    lambda: |-
      return (id(bitmask_val) & 0x02) != 0;
    device_class: problem

  - platform: template
    name: Limpiar Fuente
    lambda: |-
      return (id(bitmask_val) & 0x04) != 0;
    device_class: problem

  - platform: template
    name: Sin Agua
    lambda: |-
      return (id(bitmask_val) & 0x07) == 0x07;  // solo si están los 3 bits
    device_class: problem

  - platform: template
    name: Sin Motor
    lambda: |-
      return (id(bitmask_val) & 0x20) != 0;
    device_class: problem

  - platform: template
    name: Error Desconocido
    lambda: |-
      return (id(bitmask_val) & 0x01) != 0 || (id(bitmask_val) & 0x08) != 0;
    device_class: problem

globals:
  - id: bitmask_val
    type: uint32_t
    restore_value: no
    initial_value: '0'