substitutions:
    device_name: limpia-cristales

packages:
    device_base: !include base_devices/esp12f.yaml

esphome:
    friendly_name: Limpia cristales
    area: Cocina

uart:
    tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 9600

tuya: