substitutions:
  device_name: luz-principal-salon

packages:
  device_base: !include base_devices/yeelight-light-ceiling20.yaml
  mqtt: !include common/mqtt.yaml

esphome:
  friendly_name: Luz principal salon
  area: salon
  on_boot: 
    then:
        - light.control:
            id: ceiling_light
            brightness: 80%
            color_temperature: 2700K