substitutions:
  device_name: luz-entrada-cocina

packages:
  device_base: !include base_devices/sonoffmini.yaml
  behavior: !include common/behaviors/binary_light.yaml

esphome:
  friendly_name: Luz entrada cocina
  area: cocina
