substitutions:
  device_name: luz-principal-dormitorio

packages:
  device_base: !include base_devices/yeelight-light-ceilb.yaml
  mqtt: !include common/mqtt.yaml

esphome:
  friendly_name: Luz principal dormitorio
  area: dormitorio
  on_boot: 
    then:
        - light.control:
            id: ceiling_light
            brightness: 80%
            color_temperature: 2700K
