substitutions:
  device_name: luz-entrada-dormitorio

packages:
  device_base: !include base_devices/yeelight-light-ceilb.yaml
  mqtt: !include common/mqtt.yaml

esphome:
  friendly_name: Luz entrada dormitorio
  comment: Controlador Yeelight para luminaria regulable CCT.
  area: dormitorio
  on_boot: 
    - priority: 600
      then:
          - light.control:
              id: ceiling_light
              brightness: 80%
              color_temperature: 2700K
