substitutions:
  device_name: luz-trastero

packages:
  device_base: !include base_devices/sonoffmini.yaml
  behavior: !include common/behaviors/binary_light.yaml

esphome:
  friendly_name: Luz trastero
  area: trastero
