substitutions:
  device_name: luz-entrada-estudio

packages:
  device_base: !include base_devices/yeelight-light-ceilb.yaml
  mqtt: !include common/mqtt.yaml

esphome:
  friendly_name: Luz entrada estudio
  area: estudio
  on_boot: 
    then:
        - light.control:
            id: ceiling_light
            brightness: 100%
            color_temperature: 6500K
