substitutions:
  device_name: luz-bano-pasillo

packages:
  device_base: !include base_devices/sonoffmini.yaml
  behavior: !include common/behaviors/binary_light.yaml

esphome:
  friendly_name: Luz baño pasillo
  area: bano_pasillo
