substitutions:
  device_name: luz-principal-cocina

packages:
  device_base: !include base_devices/sonoffmini.yaml
  behavior: !include common/behaviors/binary_light.yaml

esphome:
  friendly_name: Luz principal cocina
  comment: Sonoff Mini que controla la iluminación principal.
  area: cocina
