substitutions:
  device_name: persiana-dormitorio

packages:
  device_base: !include base_devices/sonoffdualr3.yaml

esphome:
  friendly_name: Persiana dormitorio
  area: dormitorio

cover:
  - platform: current_based
    name: Persiana
    id: cover_1

    open_sensor: current_2
    open_moving_current_threshold: 0.5
    open_obstacle_current_threshold: 1
    open_duration: 15s
    open_action:
      - switch.turn_on: relay_2

    close_sensor: current_1
    close_moving_current_threshold: 0.5
    close_obstacle_current_threshold: 1
    close_duration: 15s
    close_action:
      - switch.turn_on: relay_1

    stop_action:
      - switch.turn_off: relay_2
      - switch.turn_off: relay_1

    start_sensing_delay: 0.8s

binary_sensor:
  - id: !extend switch_1
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: switch_1
            then:
              cover.close: cover_1
            else:
              cover.stop: cover_1
  - id: !extend switch_2
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: switch_2
            then:
              cover.open: cover_1
            else:
              cover.stop: cover_1