substitutions:
  device_name: rack-cpd

packages:
  device_base: !include base_devices/sonoffs60.yaml

esphome:
  friendly_name: Rack CPD
  comment: Sonoff S60 que mide y controla la alimentación del rack CPD.
  area: trastero

button:
  - platform: template
    name: Reiniciar servidor
    icon: mdi:server-off
    on_press:
      - switch.turn_off: switch_1
      - delay: 5s
      - switch.turn_on: switch_1
