substitutions:
  device_name: ventilador-rack-1

packages:
  device_base: !include base_devices/sonoffbasicr2.yaml

esphome:
  friendly_name: Ventilador 1 rack trastero
  area: trastero

fan:
  - platform: binary
    name: Ventilador
    id: fan_1
    output: relay_1
    restore_mode: RESTORE_DEFAULT_ON
