substitutions:
  device_name: consumo-electrico

packages:
  device_base: !include base_devices/esp12f.yaml

esphome:
  friendly_name: Consumo electrico
  area: pasillo

# Config anterior (hardware casero con PZEM por Modbus)
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

modbus:

sensor:
  - platform: pzemac
    id: pzemac_1
    current:
      name: Intensidad
    voltage:
      name: Voltaje
    energy:
      name: Energia
    power:
      name: Potencia
    frequency:
      name: Frecuencia
    power_factor:
      name: Actor potencia
    update_interval: 15s

button:
  - platform: template
    name: Reiniciar consumo
    on_press:
      then:
        - pzemac.reset_energy: pzemac_1
        - logger.log: Reinicio consumo electrico
