substitutions:
  device_name: difusor

packages:
  device_base: !include base_devices/esp12f.yaml

esphome:
  friendly_name: Difusor

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

tuya:


fan:
  - platform: tuya
    name: Ventilador
    switch_datapoint: 2
    speed_datapoint: 3
    speed_count: 1

light:
  - platform: tuya
    name: Luz
    switch_datapoint: 7
    color_datapoint: 10
    color_type: rgbhsv
    

binary_sensor:
  - platform: tuya
    name: Error
    sensor_datapoint: 11