substitutions:
  name: esphome-web-82e6fc
  friendly_name: ESPHome Web 82e6fc

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

sensor:
  - platform: adc
    pin: GPIO33  # Pin de entrada analógica
    name: "Botonera ADC"
    id: adc_sensor
    attenuation: auto
    update_interval: 200ms
  - platform: dallas_temp
    address: 0x343c01f0967a6728
    id: temp_1
    name: temperature
    update_interval: 15s

binary_sensor:
  - platform: template
    name: "Botón Encendido"
    lambda: |-
      return id(adc_sensor).state > 1.79 && id(adc_sensor).state < 1.88;

  - platform: template
    name: "Botón Mano"
    lambda: |-
      return id(adc_sensor).state > 2.26 && id(adc_sensor).state < 2.31;

  - platform: template
    name: "Botón Abajo"
    lambda: |-
      return id(adc_sensor).state > 2.89 && id(adc_sensor).state < 2.92;

  - platform: template
    name: "Botón Arriba"
    lambda: |-
      return id(adc_sensor).state > 2.85 && id(adc_sensor).state < 2.88;

  - platform: template
    name: "Botón OK"
    lambda: |-
      return id(adc_sensor).state > 2.63 && id(adc_sensor).state < 2.66;

  # - platform: template
  #   name: "Botón Izquierda/Volver"
  #   lambda: |-
  #     return id(adc_sensor).state > 2.71 && id(adc_sensor).state < 2.72;

output:
  - platform: gpio
    pin: GPIO25
    id: relay_1

light:
  - platform: binary
    name: Luz
    id: light_1
    output: relay_1

one_wire:
  - platform: gpio
    pin: GPIO15

display:
    platform: tm1637
    id: tm1637_display
    update_interval: 500ms
    clk_pin: GPIO13
    dio_pin: GPIO12
    length: 4
    lambda: |-
      static int i = 0;
      i++;
      if ((i % 2) == 0)
        it.printf("%.0f~C", id(temp_1).state);
      else
        it.printf("%.0f.~C", id(temp_1).state);

