substitutions:
  device_name: luz-habitacion-nestor-central

packages:
  device_base: !include base_devices/led-eglo.yaml
  mqtt: !include common/mqtt.yaml

esphome:
  friendly_name: Luz habitacion Nestor central
  area: Habitacion Nestor
  on_boot:
    then:
      - light.control:
          id: light_1
          brightness: 80%
          color_temperature: 284.7 mireds

debug:
  update_interval: 5s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    fragmentation:
      name: "Heap Fragmentation"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
