substitutions:
  device_name: test-interruptor

packages:
  device_base: !include base_devices/sonoffminir4.yaml

esphome:
  friendly_name: Test

light:
  - platform: binary
    name: Luz
    id: light_1
    output: relay_1

binary_sensor:
  - id: !extend switch_1
    on_state:
      - light.toggle: light_1
